export const INITIAL_SLIDER_PROGRESS = 288;

export const GAME_OVER_MESSAGE = {
  SOMEONE_DISCONNECTED: "SOMEONE_DISCONNECTED",
  SOMEONE_WON: "SOMEONE_WON",
  SOMEONE_LOST: "SOMEONE_LOST",
} as const;
